package com.durganmcbroom.artifact.resolver.simple.maven

import com.durganmcbroom.artifact.resolver.ArtifactReference

public typealias SimpleMavenArtifactReference = ArtifactReference<SimpleMavenArtifactMetadata, SimpleMavenArtifactStub>